name: Draft Parallel Backports

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  draft-backports:
    if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3') || contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # === Backport to v4 ===
      - name: Prepare backport branch for v4
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
        run: |
          git fetch origin v4
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}-head

          git checkout -b backport/pr-${{ github.event.pull_request.number }}-to-v4 origin/v4

          if git merge --squash pr-${{ github.event.pull_request.number }}-head; then
            git commit -m "Backport (squash) of PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
          else
            git add -A
            git commit -m "WIP: Backport of PR #${{ github.event.pull_request.number }} – contains conflicts"
          fi

      - name: Create Draft PR to v4
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: v4
          branch: backport/pr-${{ github.event.pull_request.number }}-to-v4
          title: "[Draft] Backport #${{ github.event.pull_request.number }} to v4"
          body: "Automated squash backport of PR #${{ github.event.pull_request.number }} to v4. May contain conflicts."
          draft: true
          commit-message: "Backport of PR #${{ github.event.pull_request.number }} to v4"

      # === Backport to v3 ===
      - name: Prepare backport branch for v3
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3')
        run: |
          git fetch origin v3
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}-head

          git checkout -b backport/pr-${{ github.event.pull_request.number }}-to-v3 origin/v3

          if git merge --squash pr-${{ github.event.pull_request.number }}-head; then
            git commit -m "Backport (squash) of PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
          else
            git add -A
            git commit -m "WIP: Backport of PR #${{ github.event.pull_request.number }} – contains conflicts"
          fi

      - name: Create Draft PR to v3
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: v3
          branch: backport/pr-${{ github.event.pull_request.number }}-to-v3
          title: "[Draft] Backport #${{ github.event.pull_request.number }} to v3"
          body: "Automated squash backport of PR #${{ github.event.pull_request.number }} to v3. May contain conflicts."
          draft: true
          commit-message: "Backport of PR #${{ github.event.pull_request.number }} to v3"
