name: Draft Parallel Backports

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened, ready_for_review]

jobs:
  draft-backports:
    if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3') || contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Squash PR commits
        run: |
          # Make sure we have both branches
          git fetch origin ${{ github.base_ref }}
          git fetch origin ${{ github.head_ref }}

          # Create a squash branch starting from base (e.g. main/v5)
          git checkout -b squash-temp origin/${{ github.base_ref }}

          # Squash all commits from PR branch (head_ref) into one
          git merge --squash origin/${{ github.head_ref }}
          git commit -m "Squash of PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"


      # === Draft Backport to v4 ===
      - name: Backport to v4
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
        run: |
          git fetch origin v4
          git checkout -b backport/pr-${{ github.event.pull_request.number }}-to-v4 origin/v4
          git cherry-pick squash-temp || true
          git push origin backport/pr-${{ github.event.pull_request.number }}-to-v4 --force

      - name: Create Draft PR to v4
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: v4
          branch: backport/pr-${{ github.event.pull_request.number }}-to-v4
          title: "[Draft] Backport #${{ github.event.pull_request.number }} to v4"
          body: "Automated squash backport of PR #${{ github.event.pull_request.number }} to v4 (while original PR is still in draft)."
          draft: true

      # === Draft Backport to v3 ===
      - name: Backport to v3
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3')
        run: |
          git fetch origin v3
          git checkout -b backport/pr-${{ github.event.pull_request.number }}-to-v3 origin/v3
          git cherry-pick squash-temp || true
          git push origin backport/pr-${{ github.event.pull_request.number }}-to-v3 --force

      - name: Create Draft PR to v3
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: v3
          branch: backport/pr-${{ github.event.pull_request.number }}-to-v3
          title: "[Draft] Backport #${{ github.event.pull_request.number }} to v3"
          body: "Automated squash backport of PR #${{ github.event.pull_request.number }} to v3 (while original PR is still in draft)."
          draft: true
