name: Draft Parallel Backports

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  draft-backports:
    if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3') || contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Authenticate GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git remote -v

      # === Backport to v4 ===
      - name: Squash PR commits into v4 branch
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
        run: |
          git fetch origin v4
          git checkout -b backport/pr-${{ github.event.pull_request.number }}-to-v4 origin/v4

          # Squash merge directly into backport branch
          if ! git merge --squash origin/${{ github.head_ref }}; then
            echo "⚠️ Conflicts detected, committing anyway"
          fi

          git add -A || true
          git commit -m "Backport of PR #${{ github.event.pull_request.number }} to v4 (squashed, may contain conflicts)" || true
          git push origin backport/pr-${{ github.event.pull_request.number }}-to-v4 --force

      - name: Create Draft PR to v4
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v4')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: v4
          branch: backport/pr-${{ github.event.pull_request.number }}-to-v4
          title: "[Draft] Backport #${{ github.event.pull_request.number }} to v4"
          body: "Automated squash backport of PR #${{ github.event.pull_request.number }} to v4. ⚠️ May contain conflicts."
          draft: true

      # === Backport to v3 ===
      - name: Squash PR commits into v3 branch
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3')
        run: |
          git fetch origin v3
          git checkout -b backport/pr-${{ github.event.pull_request.number }}-to-v3 origin/v3

          # Squash merge directly into backport branch
          if ! git merge --squash origin/${{ github.head_ref }}; then
            echo "⚠️ Conflicts detected, committing anyway"
          fi

          git add -A || true
          git commit -m "Backport of PR #${{ github.event.pull_request.number }} to v3 (squashed, may contain conflicts)" || true
          git push origin backport/pr-${{ github.event.pull_request.number }}-to-v3 --force

      - name: Create Draft PR to v3
        if: contains(github.event.pull_request.labels.*.name, 'backport-to-v3')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: v3
          branch: backport/pr-${{ github.event.pull_request.number }}-to-v3
          title: "[Draft] Backport #${{ github.event.pull_request.number }} to v3"
          body: "Automated squash backport of PR #${{ github.event.pull_request.number }} to v3. ⚠️ May contain conflicts."
          draft: true
